# права: welcome.admin - доступ к /welcome
#
# default отключает действия плагина и оставляет сообщения стандартными.
#
# чтобы скрыть сообщения в духе "%nick% зашел в игру"
#     в графе broadcast.join.enabled выставьте false.
#       Чтобы вызвать пустую строку, оставьте скобки пустыми.
#         broadcast.leave работает точно так же.
#
#
# broadcast отвечает за сообщения всему серверу, local - игру лично.
# тщательно проверьте конфиг перед тем, как сообщить об ошибке.
#
# все блоки "message" поддерживают кириллицу, цвета с "&", а также тэги:
#     {nick} - возвращает никнейм игрока
#     {online} - возвращает количество игроков онлайн
#
# вы можете создавать столько строк, сколько вам нужно.
#
# больше плагинов: https://vk.com/baroness_dev

local:
  join:
    enabled: true
    message:
      - 'Добро пожаловать на &2SapphireLife&f!'
      - 'Игроки онлайн: &2{online}'

  death:
    enabled: true
    message:
      - '&bПомните, что в мире SapphireLife вы бессмертны!'
      - '&bПосле каждой гибели игрок будет перемещен на ближайшую локацию возрождения.'
      - '&bСуществуют некоторые штрафные санкции, изменяющиеся в зависимости от локации,'
      - '&bуровня игрока и типа противника.'

broadcast:
  join:
    default: false
    enabled: true
    message:
      - '&7{nick} присоединился к серверу.'

  leave:
    default: false
    enabled: true
    message:
      - '&7{nick} покинул сервер.'

  death:
    default: false
    enabled: true
    message:
      - '&7{nick} умер по неизвестной причине.'
