# права: welcome.admin - доступ к /welcome
#
# Enabled активирует действие части плагина.
# Если оно отключено, сообщения останутся нетронутыми.
#
# Если вам нужно убрать сообщения (например, о входе игрока),
# установите значение "message: []" и оно будет полностью убрано.
#
#
# global отвечает за сообщения всему серверу, local - игру лично.
# тщательно проверьте конфиг перед тем, как сообщить об ошибке.
#
# все блоки "message" поддерживают кириллицу, PlaceholderAPI, цвета с "&", а также тэги:
#     {nick} - возвращает никнейм игрока
#     {online} - возвращает количество игроков онлайн
#
# вы можете создавать столько строк, сколько вам нужно.
#
# больше плагинов: https://vk.com/baroness_dev

reloadMessage: 'Welcome перезагружен.'

local:
  join:
    enabled: true
    message:
      - 'Добро пожаловать на &2SapphireLife&f!'
      - 'Игроки онлайн: &2{online}'

  death:
    enabled: true
    message:
      - '&bПомните, что в мире SapphireLife вы бессмертны!'
      - '&bПосле каждой гибели игрок будет перемещен на ближайшую локацию возрождения.'
      - '&bСуществуют некоторые штрафные санкции, изменяющиеся в зависимости от локации,'
      - '&bуровня игрока и типа противника.'

global:
  join:
    enabled: true
    message:
      - '&7{nick} присоединился к серверу.'

  leave:
    enabled: true
    message:
      - '&7{nick} покинул сервер.'

  death:
    enabled: true
    message:
      - '&7{nick} умер по неизвестной причине.'
