name: Welcome
version: 1.7
main: ru.baronessdev.welcome.Core
authors: [Black_Baroness]
description: Продвинутый менеджер приветствий и прощальных сообщений.
website: https://vk.com/baroness_dev
commands:
  welcome:
    usage: /welcome