name: Welcome
version: 1.5
main: plugins.baroness.Core
authors: [Black_Baroness]
description: Продвинутый менеджер приветствий и прощальных сообщений.
website: https://vk.com/baroness_plugins
commands:
  welcome:
    usage: /welcome