name: Welcome
version: ${project.version}
main: ru.baronessdev.free.welcome.Welcome
authors: [Black_Baroness]
description: Продвинутый менеджер приветствий, смертей и прощальных сообщений.
website: baronessdev.ru
softdepend:
  - PlaceholderAPI
commands:
  welcome:
    usage: /welcome
    permission: welcome.admin